server:
  port: 19000 #工程端口
logging:
    level:
      root: info
    file:
      path: log
open:
  ai:
    apiBaseUrl: https://api.openai.com
    authorization: Bearer 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
