server:
  port: 19000 #工程端口
logging:
    level:
      root: info
    file:
      path: log
open:
  ai:
    apiBaseUrl: https://api.openai.com
    authorization: Bearer xxxxxxxxxxxxxxx
spring:
  application:
    name: chatgpt-java
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: true